### PR TITLE
Fix preset config

### PR DESCRIPTION
**Pull request by JGiter**

### CODE REVIEW

**Comment by jrhender** [comment]
@JGiter Do you have a link to the documentation of the config that is changing in this PR?

**Comment by JGiter** [comment]
> @JGiter Do you have a link to the documentation of the config that is changing in this PR?

Yes, added it now

**Comment by jrhender** [comment]
Ah okay. I guess I'm wondering what the difference is between `parserConfig` and `presetConfig`. Do you have any details about this?

**Comment by JGiter** [comment]
Ah, got it. Added it as well

**Comment by jrhender** [comment]
Thanks. I'm taking a look at https://github.com/semantic-release/release-notes-generator#options but it's not obvious to me what the difference is between `presetConfig` and `parserConfig`. Is it clear to you why change will work?

**Comment by JGiter** [comment]
I think parser just extracts message parts and preset creates the release note from these parts

**Review by jrhender — APPROVED** [review]
Sounds good, let's give it a try

**Pull request merged**
